kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubeflow-operator
subjects:
- kind: ServiceAccount
  name: kubeflow-operator
  namespace: $(namespace) # Replace it with operator's namespace
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
