apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeflow-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kubeflow-operator
  template:
    metadata:
      labels:
        name: kubeflow-operator
    spec:
      serviceAccountName: kubeflow-operator
      containers:
        - name: kubeflow-operator
          # Replace this with the built image name
          image: aipipeline/kubeflow-operator:latest
          command:
          - kfctl
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
